services:
  postgres:
    image: postgres:15-alpine
    container_name: zabbix-postgres
    environment:
      POSTGRES_PASSWORD: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_DB: zabbix
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - dorothy-network
      
  # Servidor Zabbix
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:ubuntu-7.0-latest
    container_name: zabbix-server
    depends_on:
      - postgres
    environment:
      DB_SERVER_HOST: postgres
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      ZBX_TIMEOUT: 30
    ports:
      - "10051:10051"
    restart: unless-stopped
    networks:
      - dorothy-network

  # Interface Web do Zabbix
  zabbix-web:
    image: zabbix/zabbix-web-apache-pgsql:ubuntu-7.0-latest
    container_name: zabbix-web
    depends_on:
      - postgres
      - zabbix-server
    environment:
      DB_SERVER_HOST: postgres
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: America/Sao_Paulo
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - dorothy-network

  # Agente Zabbix para monitorar o próprio servidor
  zabbix-agent-server:
    image: zabbix/zabbix-agent2:ubuntu-7.0-latest
    container_name: zabbix-agent-server
    hostname: zabbix-server
    depends_on:
      - zabbix-server
    environment:
      ZBX_HOSTNAME: Zabbix-Server
      ZBX_SERVER_HOST: zabbix-server
    restart: unless-stopped
    privileged: true
    networks:
      - dorothy-network

  # Agente Zabbix para simular problemas
  zabbix-agent-simulator:
    build:
      context: ../host
      dockerfile: Dockerfile
    container_name: zabbix-agent-simulator
    hostname: simulator
    depends_on:
      - zabbix-server
    environment:
      ZBX_HOSTNAME: Problem-Simulator
      ZBX_SERVER_HOST: zabbix-server
      ZBX_ACTIVE_SERVER: zabbix-server
    volumes:
      - ../host:/etc/zabbix/scripts
      - rundeck-scripts:/usr/local/bin
      - simulator-logs:/var/log/results
    ports:
      - "10050:10050"
    restart: unless-stopped
    privileged: true  
    networks:
      - dorothy-network

  # API Dorothy
  dorothy-api:
    image: dorothy-api
    container_name: dorothy-api
    environment:
      - LOG_LEVEL=debug
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_MODEL=llama3.2
      - RUNDECK_API_URL=http://rundeck:4440/api/41
      - RUNDECK_TOKEN=admin12345
      - RUNDECK_PROJECT=automated-ops
      - RUNDECK_JOB_CLEANUP_DISK=cleanup-disk
      - RUNDECK_JOB_RESTART_SERVICE=restart-service
      - RUNDECK_JOB_ANALYZE_PROCESSES=analyze-processes
      - RUNDECK_JOB_RESTART_APPLICATION=restart-application
      - RUNDECK_JOB_NOTIFY=notify
    ports:
      - "8000:8000"
    volumes:
      - api-logs:/app/logs
    networks:
      - dorothy-network
    restart: unless-stopped
    depends_on:
      - ollama
      - rundeck

  # Ollama para LLMs locais
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama-data:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - dorothy-network
    restart: unless-stopped
    command: serve
    
  # Banco de dados para o Rundeck
  rundeck-mariadb:
    image: mariadb:10.6
    container_name: rundeck-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rundeckrootpw
      MYSQL_DATABASE: rundeck
      MYSQL_USER: rundeck
      MYSQL_PASSWORD: rundeck
    volumes:
      - rundeck-db:/var/lib/mysql
    restart: unless-stopped
    networks:
      - dorothy-network

  # Rundeck - plataforma de automação
  rundeck:
    image: rundeck/rundeck:4.17.2
    container_name: rundeck
    depends_on:
      - rundeck-mariadb
    environment:
      RUNDECK_DATABASE_URL: jdbc:mysql://rundeck-mariadb/rundeck?autoReconnect=true&useSSL=false
      RUNDECK_DATABASE_DRIVER: org.mariadb.jdbc.Driver
      RUNDECK_DATABASE_USERNAME: rundeck
      RUNDECK_DATABASE_PASSWORD: rundeck
      RUNDECK_GRAILS_URL: http://localhost:4440
      RUNDECK_SERVER_FORWARDED: "true"
      RUNDECK_LOGGING_STRATEGY: CONSOLE
      RUNDECK_PREAUTH_ENABLED: "false"
      RUNDECK_SECURITY_CSRF_ENABLED: "false"
      RUNDECK_SECURITY_APITOKEN_ADMIN_DURATION: forever
      RUNDECK_USER_ADMIN_PASSWORD: admin12345
      SIMULATOR_HOST: zabbix-agent-simulator
    volumes:
      - rundeck-data:/home/rundeck/server/data
      - ./rundeck/jobs:/home/rundeck/jobs
      - ./rundeck/scripts:/home/rundeck/scripts:ro
      - ./rundeck/keys:/home/rundeck/etc/keys
      - ./rundeck/logs:/var/lib/rundeck/logs
      - simulator-logs:/var/rundeck/simulator-logs:ro
      - ./rundeck/rundeck-config.properties:/home/rundeck/server/config/rundeck-config.properties
      - simulator-logs:/var/lib/rundeck/logs/simulator:ro
      - rundeck-scripts:/home/rundeck/rundeck-scripts
    ports:
      - "4440:4440"
    restart: unless-stopped
    networks:
      - dorothy-network

networks:
  dorothy-network:
    driver: bridge

volumes:
  postgres-data:
  ollama-data:
  simulator-scripts:
  simulator-logs:
  rundeck-data:
  rundeck-db:
  rundeck-scripts:
  api-logs: